Create index.html, app.js, display Hello World
greg19850/Budget-Planner-Project pull request #1
Opened 2020-08-30 18:26 UTC by greg19850

2020-09-04 15:49 UTC, mperwejnis requested changes
jeden komentarz do poprawy

2020-09-04 15:49 UTC, mperwejnis commented on .gitignore
> +node_modules/
katalog dist/ powinien także znajdować się w gitignore - nie powinien znajdować się w repo

2020-09-04 15:49 UTC, mperwejnis commented on package.json
> +    "start": "webpack-dev-server --hot --open",
super 👍

2020-09-04 18:07 UTC, greg19850 commented on .gitignore
> +node_modules/
folder dist dodany

2020-09-05 08:00 UTC, mperwejnis approved these changes

2020-09-05 10:42 UTC, merged