Create add income structure and logic
greg19850/Budget-Planner-Project pull request #4
Opened 2020-09-29 18:59 UTC by greg19850

2020-09-30 13:21 UTC, mperwejnis requested changes
Dodalam jeden komentarz

2020-09-30 13:21 UTC, mperwejnis commented on src/components/balance/Balance.js
> +  const income = useSelector((state) => state.accountSummary.incomeSummary);
Proponuję utworzyć plik z selektorami: src/selectors/AccountSummary.js i tam utworzyć selector np getBalance() który zwróci nam to co obliczasz tutaj (income - expense). Dzięki temu selector będzie dostępny również z innego miejsca. To samo zrobiłabym z getIcome i getOutcome - będzie wtedy jedno miejsce gdzie bedą dostępne selektory.

2020-09-30 19:22 UTC, greg19850 commented
Ok, zrobiłem zmiany, ale mam dziwne wrażenie, że to nie do końca o to Ci chodziło...I nie bardzo rozumiem czemu ma zrobić selektory do getIncome i getExpense, skoro ich wartość jest w state, więc mam dostęp do nich wszędzie.

2020-10-01 12:58 UTC, mperwejnis approved these changes

2020-10-01 17:00 UTC, merged